/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as batchAuctionSol from "./BatchAuction.sol";
export type { batchAuctionSol };
export type { GreenShoeVault } from "./GreenShoeVault";
export type { MockERC20 } from "./MockERC20";
