/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BatchAuctionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "GREEN_SHOE_RATIO"
      | "ROUND_DURATION"
      | "auctionToken"
      | "currentRoundId"
      | "deposit"
      | "executeClearing"
      | "getSupplyStats"
      | "greenShoeVault"
      | "isRoundActive"
      | "isWhitelisted"
      | "lastClearingTime"
      | "maxClearingPrice"
      | "minClearingPrice"
      | "owner"
      | "pause"
      | "paused"
      | "paymentCurrency"
      | "priceTolerance"
      | "renounceOwnership"
      | "rounds"
      | "setDynamicSupplyParams"
      | "setGreenShoeVault"
      | "setPriceRange"
      | "setTokenSupplyPerRound"
      | "setTotalTokenSupply"
      | "setWhitelist"
      | "startNextRound"
      | "supplyAdjustmentStep"
      | "targetPrice"
      | "tokenSupplyPerRound"
      | "totalTokenSupply"
      | "totalTokensIssued"
      | "transferOwnership"
      | "unpause"
      | "userBalances"
      | "userTokenBalances"
      | "withdraw"
      | "withdrawProceeds"
      | "withdrawTokens"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposit"
      | "EmergencyWithdraw"
      | "GreenShoeActivated"
      | "OwnershipTransferred"
      | "Paused"
      | "PriceRangeUpdated"
      | "ProceedsWithdrawn"
      | "RoundCleared"
      | "RoundStarted"
      | "SupplyAdjusted"
      | "TargetPriceUpdated"
      | "TokensAllocated"
      | "TokensWithdrawn"
      | "TotalSupplyUpdated"
      | "Unpaused"
      | "Withdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "GREEN_SHOE_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROUND_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auctionToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentRoundId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeClearing",
    values: [BigNumberish, AddressLike[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupplyStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "greenShoeVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRoundActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastClearingTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxClearingPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minClearingPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentCurrency",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceTolerance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rounds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDynamicSupplyParams",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGreenShoeVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceRange",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenSupplyPerRound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTotalTokenSupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelist",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "startNextRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supplyAdjustmentStep",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenSupplyPerRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTokenSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTokensIssued",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTokenBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawProceeds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTokens",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "GREEN_SHOE_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROUND_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auctionToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeClearing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupplyStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "greenShoeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRoundActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastClearingTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxClearingPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minClearingPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceTolerance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rounds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDynamicSupplyParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGreenShoeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenSupplyPerRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTotalTokenSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startNextRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supplyAdjustmentStep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenSupplyPerRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTokenSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTokensIssued",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTokenBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawProceeds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTokens",
    data: BytesLike
  ): Result;
}

export namespace DepositEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GreenShoeActivatedEvent {
  export type InputTuple = [amountLocked: BigNumberish];
  export type OutputTuple = [amountLocked: bigint];
  export interface OutputObject {
    amountLocked: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceRangeUpdatedEvent {
  export type InputTuple = [minPrice: BigNumberish, maxPrice: BigNumberish];
  export type OutputTuple = [minPrice: bigint, maxPrice: bigint];
  export interface OutputObject {
    minPrice: bigint;
    maxPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProceedsWithdrawnEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundClearedEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    clearingPrice: BigNumberish,
    totalVolume: BigNumberish
  ];
  export type OutputTuple = [
    roundId: bigint,
    clearingPrice: bigint,
    totalVolume: bigint
  ];
  export interface OutputObject {
    roundId: bigint;
    clearingPrice: bigint;
    totalVolume: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundStartedEvent {
  export type InputTuple = [roundId: BigNumberish, startTime: BigNumberish];
  export type OutputTuple = [roundId: bigint, startTime: bigint];
  export interface OutputObject {
    roundId: bigint;
    startTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupplyAdjustedEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    newSupply: BigNumberish,
    lastPrice: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    roundId: bigint,
    newSupply: bigint,
    lastPrice: bigint,
    reason: string
  ];
  export interface OutputObject {
    roundId: bigint;
    newSupply: bigint;
    lastPrice: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetPriceUpdatedEvent {
  export type InputTuple = [newTargetPrice: BigNumberish];
  export type OutputTuple = [newTargetPrice: bigint];
  export interface OutputObject {
    newTargetPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensAllocatedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensWithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TotalSupplyUpdatedEvent {
  export type InputTuple = [newTotalSupply: BigNumberish];
  export type OutputTuple = [newTotalSupply: bigint];
  export interface OutputObject {
    newTotalSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BatchAuction extends BaseContract {
  connect(runner?: ContractRunner | null): BatchAuction;
  waitForDeployment(): Promise<this>;

  interface: BatchAuctionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  GREEN_SHOE_RATIO: TypedContractMethod<[], [bigint], "view">;

  ROUND_DURATION: TypedContractMethod<[], [bigint], "view">;

  auctionToken: TypedContractMethod<[], [string], "view">;

  currentRoundId: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  executeClearing: TypedContractMethod<
    [
      _price: BigNumberish,
      winners: AddressLike[],
      tokenAmounts: BigNumberish[],
      costAmounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  getSupplyStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        total: bigint;
        issued: bigint;
        remaining: bigint;
        current: bigint;
        progress: bigint;
      }
    ],
    "view"
  >;

  greenShoeVault: TypedContractMethod<[], [string], "view">;

  isRoundActive: TypedContractMethod<[], [boolean], "view">;

  isWhitelisted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lastClearingTime: TypedContractMethod<[], [bigint], "view">;

  maxClearingPrice: TypedContractMethod<[], [bigint], "view">;

  minClearingPrice: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  paymentCurrency: TypedContractMethod<[], [string], "view">;

  priceTolerance: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rounds: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        clearingPrice: bigint;
        totalTokensSold: bigint;
        isCleared: boolean;
      }
    ],
    "view"
  >;

  setDynamicSupplyParams: TypedContractMethod<
    [_target: BigNumberish, _step: BigNumberish, _tolerance: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGreenShoeVault: TypedContractMethod<
    [_vault: AddressLike],
    [void],
    "nonpayable"
  >;

  setPriceRange: TypedContractMethod<
    [_minPrice: BigNumberish, _maxPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenSupplyPerRound: TypedContractMethod<
    [_supply: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTotalTokenSupply: TypedContractMethod<
    [_totalSupply: BigNumberish],
    [void],
    "nonpayable"
  >;

  setWhitelist: TypedContractMethod<
    [users: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;

  startNextRound: TypedContractMethod<[], [void], "nonpayable">;

  supplyAdjustmentStep: TypedContractMethod<[], [bigint], "view">;

  targetPrice: TypedContractMethod<[], [bigint], "view">;

  tokenSupplyPerRound: TypedContractMethod<[], [bigint], "view">;

  totalTokenSupply: TypedContractMethod<[], [bigint], "view">;

  totalTokensIssued: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userTokenBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  withdrawProceeds: TypedContractMethod<[], [void], "nonpayable">;

  withdrawTokens: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "GREEN_SHOE_RATIO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROUND_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "auctionToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentRoundId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeClearing"
  ): TypedContractMethod<
    [
      _price: BigNumberish,
      winners: AddressLike[],
      tokenAmounts: BigNumberish[],
      costAmounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getSupplyStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        total: bigint;
        issued: bigint;
        remaining: bigint;
        current: bigint;
        progress: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "greenShoeVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isRoundActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWhitelisted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastClearingTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxClearingPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minClearingPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentCurrency"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceTolerance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rounds"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        clearingPrice: bigint;
        totalTokensSold: bigint;
        isCleared: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setDynamicSupplyParams"
  ): TypedContractMethod<
    [_target: BigNumberish, _step: BigNumberish, _tolerance: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGreenShoeVault"
  ): TypedContractMethod<[_vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceRange"
  ): TypedContractMethod<
    [_minPrice: BigNumberish, _maxPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenSupplyPerRound"
  ): TypedContractMethod<[_supply: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTotalTokenSupply"
  ): TypedContractMethod<[_totalSupply: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWhitelist"
  ): TypedContractMethod<
    [users: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startNextRound"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supplyAdjustmentStep"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "targetPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenSupplyPerRound"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalTokenSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalTokensIssued"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userTokenBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawProceeds"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawTokens"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "GreenShoeActivated"
  ): TypedContractEvent<
    GreenShoeActivatedEvent.InputTuple,
    GreenShoeActivatedEvent.OutputTuple,
    GreenShoeActivatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PriceRangeUpdated"
  ): TypedContractEvent<
    PriceRangeUpdatedEvent.InputTuple,
    PriceRangeUpdatedEvent.OutputTuple,
    PriceRangeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProceedsWithdrawn"
  ): TypedContractEvent<
    ProceedsWithdrawnEvent.InputTuple,
    ProceedsWithdrawnEvent.OutputTuple,
    ProceedsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "RoundCleared"
  ): TypedContractEvent<
    RoundClearedEvent.InputTuple,
    RoundClearedEvent.OutputTuple,
    RoundClearedEvent.OutputObject
  >;
  getEvent(
    key: "RoundStarted"
  ): TypedContractEvent<
    RoundStartedEvent.InputTuple,
    RoundStartedEvent.OutputTuple,
    RoundStartedEvent.OutputObject
  >;
  getEvent(
    key: "SupplyAdjusted"
  ): TypedContractEvent<
    SupplyAdjustedEvent.InputTuple,
    SupplyAdjustedEvent.OutputTuple,
    SupplyAdjustedEvent.OutputObject
  >;
  getEvent(
    key: "TargetPriceUpdated"
  ): TypedContractEvent<
    TargetPriceUpdatedEvent.InputTuple,
    TargetPriceUpdatedEvent.OutputTuple,
    TargetPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensAllocated"
  ): TypedContractEvent<
    TokensAllocatedEvent.InputTuple,
    TokensAllocatedEvent.OutputTuple,
    TokensAllocatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensWithdrawn"
  ): TypedContractEvent<
    TokensWithdrawnEvent.InputTuple,
    TokensWithdrawnEvent.OutputTuple,
    TokensWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "TotalSupplyUpdated"
  ): TypedContractEvent<
    TotalSupplyUpdatedEvent.InputTuple,
    TotalSupplyUpdatedEvent.OutputTuple,
    TotalSupplyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;

  filters: {
    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "EmergencyWithdraw(address,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "GreenShoeActivated(uint256)": TypedContractEvent<
      GreenShoeActivatedEvent.InputTuple,
      GreenShoeActivatedEvent.OutputTuple,
      GreenShoeActivatedEvent.OutputObject
    >;
    GreenShoeActivated: TypedContractEvent<
      GreenShoeActivatedEvent.InputTuple,
      GreenShoeActivatedEvent.OutputTuple,
      GreenShoeActivatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PriceRangeUpdated(uint256,uint256)": TypedContractEvent<
      PriceRangeUpdatedEvent.InputTuple,
      PriceRangeUpdatedEvent.OutputTuple,
      PriceRangeUpdatedEvent.OutputObject
    >;
    PriceRangeUpdated: TypedContractEvent<
      PriceRangeUpdatedEvent.InputTuple,
      PriceRangeUpdatedEvent.OutputTuple,
      PriceRangeUpdatedEvent.OutputObject
    >;

    "ProceedsWithdrawn(address,uint256)": TypedContractEvent<
      ProceedsWithdrawnEvent.InputTuple,
      ProceedsWithdrawnEvent.OutputTuple,
      ProceedsWithdrawnEvent.OutputObject
    >;
    ProceedsWithdrawn: TypedContractEvent<
      ProceedsWithdrawnEvent.InputTuple,
      ProceedsWithdrawnEvent.OutputTuple,
      ProceedsWithdrawnEvent.OutputObject
    >;

    "RoundCleared(uint256,uint256,uint256)": TypedContractEvent<
      RoundClearedEvent.InputTuple,
      RoundClearedEvent.OutputTuple,
      RoundClearedEvent.OutputObject
    >;
    RoundCleared: TypedContractEvent<
      RoundClearedEvent.InputTuple,
      RoundClearedEvent.OutputTuple,
      RoundClearedEvent.OutputObject
    >;

    "RoundStarted(uint256,uint256)": TypedContractEvent<
      RoundStartedEvent.InputTuple,
      RoundStartedEvent.OutputTuple,
      RoundStartedEvent.OutputObject
    >;
    RoundStarted: TypedContractEvent<
      RoundStartedEvent.InputTuple,
      RoundStartedEvent.OutputTuple,
      RoundStartedEvent.OutputObject
    >;

    "SupplyAdjusted(uint256,uint256,uint256,string)": TypedContractEvent<
      SupplyAdjustedEvent.InputTuple,
      SupplyAdjustedEvent.OutputTuple,
      SupplyAdjustedEvent.OutputObject
    >;
    SupplyAdjusted: TypedContractEvent<
      SupplyAdjustedEvent.InputTuple,
      SupplyAdjustedEvent.OutputTuple,
      SupplyAdjustedEvent.OutputObject
    >;

    "TargetPriceUpdated(uint256)": TypedContractEvent<
      TargetPriceUpdatedEvent.InputTuple,
      TargetPriceUpdatedEvent.OutputTuple,
      TargetPriceUpdatedEvent.OutputObject
    >;
    TargetPriceUpdated: TypedContractEvent<
      TargetPriceUpdatedEvent.InputTuple,
      TargetPriceUpdatedEvent.OutputTuple,
      TargetPriceUpdatedEvent.OutputObject
    >;

    "TokensAllocated(address,uint256)": TypedContractEvent<
      TokensAllocatedEvent.InputTuple,
      TokensAllocatedEvent.OutputTuple,
      TokensAllocatedEvent.OutputObject
    >;
    TokensAllocated: TypedContractEvent<
      TokensAllocatedEvent.InputTuple,
      TokensAllocatedEvent.OutputTuple,
      TokensAllocatedEvent.OutputObject
    >;

    "TokensWithdrawn(address,uint256)": TypedContractEvent<
      TokensWithdrawnEvent.InputTuple,
      TokensWithdrawnEvent.OutputTuple,
      TokensWithdrawnEvent.OutputObject
    >;
    TokensWithdrawn: TypedContractEvent<
      TokensWithdrawnEvent.InputTuple,
      TokensWithdrawnEvent.OutputTuple,
      TokensWithdrawnEvent.OutputObject
    >;

    "TotalSupplyUpdated(uint256)": TypedContractEvent<
      TotalSupplyUpdatedEvent.InputTuple,
      TotalSupplyUpdatedEvent.OutputTuple,
      TotalSupplyUpdatedEvent.OutputObject
    >;
    TotalSupplyUpdated: TypedContractEvent<
      TotalSupplyUpdatedEvent.InputTuple,
      TotalSupplyUpdatedEvent.OutputTuple,
      TotalSupplyUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Withdraw(address,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
