/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGreenShoe,
  IGreenShoeInterface,
} from "../../../contracts/BatchAuction.sol/IGreenShoe";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "depositStabilizationFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGreenShoe__factory {
  static readonly abi = _abi;
  static createInterface(): IGreenShoeInterface {
    return new Interface(_abi) as IGreenShoeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IGreenShoe {
    return new Contract(address, _abi, runner) as unknown as IGreenShoe;
  }
}
